spring.datasource.url=jdbc:${{Postgres.DATABASE_URL}}/tg_bot_reminder?sslmode=require&stringtype=unspecified
spring.datasource.username=${{Postgres.POSTGRES_USER}}
spring.datasource.password=${{Posgres.POSTGRES_PASSWORD}
telegram.bot.token=8378047085:AAG_TPAY29__xvCnICgNlbblU9VCeYoCzKE
#spring.datasource.url=jdbc:postgresql://localhost:5432/notification_task
#spring.datasource.username=tgAdmin
#spring.datasource.password=jaeCoo
#telegram.bot.token=
spring.datasource.driver-class-name=org.postgresql.Driver
#???????????? JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.connection.charSet=UTF-8
spring.jpa.properties.hibernate.connection.characterEncoding=UTF-8
spring.jpa.properties.hibernate.connection.useUnicode=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
#spring.jpa.defer-datasource-initialization=true

#spring.sql.init.mode=always
#spring.datasource.initialization-mode=ALWAYS
spring.liquibase.enabled=false
#spring.liquibase.change-log=classpath:liquibase/changelog/changelog-master.yaml
spring.liquibase.default-schema=public
spring.liquibase.liquibase-schema=public
spring.liquibase.show-sql=true
spring.liquibase.format-sql=true
spring.jpa.defer-datasource-initialization=true
server.port=8080
