spring.datasource.url=jdbc:postgresql:****@ep-b017b263fdc1.kaiki.ru:5432/tg_bot_reminder?sslmode=require&sslhostnameverifier=org.postgresql.ssl.NaiveHostnameVerifier&stringtype=unspecified
spring.datasource.username=kaiki_owner
spring.datasource.password=CNZVO6KsuWwi.mPMnWOFAKJ0
telegram.bot.token=8378047085:AAG_TPAY29__xvCnICgNlbblU9VCeYoCzKE
spring.datasource.url=jdbc:postgresql://localhost:5432/notification_task
spring.datasource.username=tgAdmin
spring.datasource.password=jaeCoo
telegram.bot.token=
spring.datasource.driver-class-name=org.postgresql.Driver
#???????????? JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.connection.charSet=UTF-8
spring.jpa.properties.hibernate.connection.characterEncoding=UTF-8
spring.jpa.properties.hibernate.connection.useUnicode=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

#spring.sql.init.mode=always
#spring.datasource.initialization-mode=ALWAYS
spring.liquibase.enabled=false
#spring.liquibase.change-log=classpath:liquibase/changelog/changelog-master.yaml
spring.liquibase.default-schema=public
spring.liquibase.liquibase-schema=public
spring.liquibase.show-sql=true
spring.liquibase.format-sql=true
spring.jpa.defer-datasource-initialization=true
