spring.datasource.url=jdbc:postgresql://kodama.proxy.rlwy.net:47714/railway?sslmode=require&stringtype=unspecified
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
telegram.bot.token=${BOT_TOKEN}
spring.datasource.driver-class-name=org.postgresql.Driver
#???????????? JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.connection.charSet=UTF-8
spring.jpa.properties.hibernate.connection.characterEncoding=UTF-8
spring.jpa.properties.hibernate.connection.useUnicode=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

spring.liquibase.enabled=false
spring.liquibase.default-schema=public
spring.liquibase.liquibase-schema=public
spring.liquibase.show-sql=true
spring.liquibase.format-sql=true
spring.jpa.defer-datasource-initialization=true
server.port=8080
